// Copyright (c) 2026 Joran
// SPDX-License-Identifier: MIT

//! Lightweight i18n (Chinese / English) for the UI and messages.

use std::sync::atomic::{AtomicBool, Ordering};

static IS_ZH: AtomicBool = AtomicBool::new(false);

/// Set the active language. `true` = Chinese.
pub fn set_zh(zh: bool) {
    IS_ZH.store(zh, Ordering::Relaxed);
}

pub fn is_zh() -> bool {
    IS_ZH.load(Ordering::Relaxed)
}

/// Look up `key` in the active language. Falls back to the key itself.
pub fn t(key: &str) -> String {
    if is_zh() { zh(key) } else { en(key) }
}

fn zh(key: &str) -> String {
    match key {
    "WindowTitle" => "USBIP 设备管理器".to_owned(),
    "Settings" => "设置".to_owned(),
    "Device" => "已连接设备".to_owned(),
    "Persisted" => "持久化设备".to_owned(),
    "AutoAttach" => "自动附加".to_owned(),
    "Light" => "亮色".to_owned(),
    "Dark" => "暗色".to_owned(),
    "Language" => "语言".to_owned(),
    "English" => "English".to_owned(),
    "Chinese" => "中文".to_owned(),
    "Exit" => "退出".to_owned(),
    "SpecifyNetworkCard" => "指定绑定/附加设备的网卡".to_owned(),
    "ClosToTray" => "关闭到托盘(后台运行)".to_owned(),
    "UseBusID" => "使用BusID绑定/附加设备".to_owned(),
    "ToolTipSpecifyNetworkCard" => "指定WSL可以访问Windows的网卡。".to_owned(),
    "ToolTipForwardNetCard" => "选择转发USB IP数据的网卡".to_owned(),
    "ToolTipUseBusID" => "使用BusID来绑定/附加设备(默认使用HardwareID)".to_owned(),
    "SelectNetCart" => "选择网卡".to_owned(),
    "OK" => "确定".to_owned(),
    "Cancel" => "取消".to_owned(),
    "Refresh" => "刷新设备".to_owned(),
    "ResetConfig" => "恢复默认配置".to_owned(),
    "ClearLogFiles" => "清除历史日志".to_owned(),
    "OpenCinfigPath" => "打开配置目录".to_owned(),
    "DeviceInfo" => "设备信息:".to_owned(),
    "InstanceID" => "实例标识".to_owned(),
    "HardwareID" => "硬件标识".to_owned(),
    "BusID" => "总线标识".to_owned(),
    "Description" => "设备描述".to_owned(),
    "Connected" => "已连接".to_owned(),
    "ForceBind" => "强制绑定".to_owned(),
    "Bound" => "绑定".to_owned(),
    "Attached" => "附加".to_owned(),
    "ClientIP" => "客户端IP".to_owned(),
    "PersistedGUID" => "持久化标识符".to_owned(),
    "StubInstanceID" => "Stub Instance ID".to_owned(),
    "WindowsUSBDevice" => "Windows USB设备列表".to_owned(),
    "Bind" => "绑定".to_owned(),
    "Unbind" => "解绑".to_owned(),
    "Attach" => "附加".to_owned(),
    "Detach" => "分离".to_owned(),
    "Hide" => "隐藏".to_owned(),
    "Show" => "显示".to_owned(),
    "ShowHide" => "显示隐藏".to_owned(),
    "AddToAuto" => "添加到自动附加".to_owned(),
    "RemoveFromAuto" => "从自动附加移除".to_owned(),
    "DeleteSelected" => "删除选中".to_owned(),
    "DeleteAll" => "删除全部".to_owned(),
    "PersistedDevices" => "持久化(已绑定但未连接)设备列表".to_owned(),
    "AutoAttachHeaderTitle" => "自动附加设备列表".to_owned(),
    "Error" => "错误".to_owned(),
    "Note" => "提示".to_owned(),
    "NoDeviceSelected" => "没有选中的设备".to_owned(),
    "NoConnectedDevice" => "未发现已连接的USB设备。".to_owned(),
    "NoPersistedDevice" => "没有持久化设备。".to_owned(),
    "NoAutoDevice" => "自动附加列表为空。".to_owned(),
    "ShowingHiddenHint" => "当前显示隐藏设备，使用右键菜单恢复显示".to_owned(),
    "Loading" => "正在加载...".to_owned(),
    "HistoryLogsCleared" => "历史日志已删除。".to_owned(),
    "ConfigReset" => "配置已恢复为默认值。".to_owned(),
    "AnotherInstance" => "程序已在运行，请在系统托盘图标处恢复窗口。".to_owned(),
    "UsbipdCheckFailed" => "usbipd-win 检查失败".to_owned(),
    "BindSuccess" => "设备已绑定".to_owned(),
    "UnbindSuccess" => "设备已解绑".to_owned(),
    "AttachSuccess" => "设备已附加到 WSL".to_owned(),
    "DetachSuccess" => "设备已从 WSL 分离".to_owned(),
    "AttachAllSuccess" => "已分离全部设备".to_owned(),
    "DeviceInAutoAttaching" => "设备正在自动附加中。".to_owned(),
    "UsbipdNotInstalled" => "检测到usbipd-win未安装。请访问 https://github.com/dorssel/usbipd-win/releases 下载V4.4.0及更高版本的usbipd-win并安装，然后重启本程序。".to_owned(),
    "UsbipdLowVersion" => "检测到usbipd-win版本低于V4.4.0。请访问 https://github.com/dorssel/usbipd-win/releases 下载V4.4.0及更高版本的usbipd-win并安装，然后重启本程序。".to_owned(),
    "UsbipdRemoteDisk" => "检测到usbipd-win可能安装在远程磁盘中，请将usbipd-win安装到本地磁盘，然后重启本程序。".to_owned(),
    "FirewallBlocked" => "防火墙阻止了来自WSL中的连接请求.".to_owned(),
    "NoWslRunning" => "未检测到正在运行的WSL2分发版，请保持WSL2分发版处于运行状态。".to_owned(),
    "DeviceUsedByWindows" => "该设备貌似正在被Windows使用中，请停止使用该设备的服务，或者强制绑定该设备后再附加。".to_owned(),
    "ErrMsgBindFail" => "无法绑定设备".to_owned(),
    "ErrMsgUnbindFail" => "无法解绑设备".to_owned(),
    "ErrMsgAttachFail" => "无法附加设备".to_owned(),
    "ErrMsgDetachFail" => "无法分离设备".to_owned(),
    "ErrMsgDeviceNotConnected" => "设备未连接".to_owned(),
    "ErrMsgDeviceNotBound" => "设备未绑定".to_owned(),
    "ErrNoNetCard" => "网卡不可用。".to_owned(),
    "ErrNetCardEmpty" => "网卡名称为空。".to_owned(),
    "ConnectedToWsl" => "已连接到 WSL".to_owned(),
    "ConnectedToWindows" => "已连接到 Windows".to_owned(),
    "Disconnected" => "已断开连接".to_owned(),
    "AutoAttachDaemonExit" => "运行于WSL中的自动附加程序已退出。".to_owned(),
    "CanceledByUser" => "操作被取消(用户取消了管理员授权)。".to_owned(),
        _ => key.to_owned(),
    }
}

fn en(key: &str) -> String {
    match key {
    "WindowTitle" => "USBIP Device Manager".to_owned(),
    "Settings" => "Settings".to_owned(),
    "Device" => "Device".to_owned(),
    "Persisted" => "Persisted".to_owned(),
    "AutoAttach" => "Auto Attach".to_owned(),
    "Light" => "Light".to_owned(),
    "Dark" => "Dark".to_owned(),
    "Language" => "Language".to_owned(),
    "English" => "English".to_owned(),
    "Chinese" => "中文".to_owned(),
    "Exit" => "Exit".to_owned(),
    "SpecifyNetworkCard" => "Specify the Network Card".to_owned(),
    "ClosToTray" => "Close to tray (Run in background)".to_owned(),
    "UseBusID" => "Bind/Attach devices using BusID".to_owned(),
    "ToolTipSpecifyNetworkCard" => "Specify the network card that WSL can access Windows.".to_owned(),
    "ToolTipForwardNetCard" => "Select the network card for forwarding USB IP data".to_owned(),
    "ToolTipUseBusID" => "Bind/attach devices using BusID (HardwareID is used by default)".to_owned(),
    "SelectNetCart" => "Select a network card".to_owned(),
    "OK" => "OK".to_owned(),
    "Cancel" => "Cancel".to_owned(),
    "Refresh" => "Refresh".to_owned(),
    "ResetConfig" => "Restore default config".to_owned(),
    "ClearLogFiles" => "Clear history logs".to_owned(),
    "OpenCinfigPath" => "Open config path".to_owned(),
    "DeviceInfo" => "Device information:".to_owned(),
    "InstanceID" => "Instance ID".to_owned(),
    "HardwareID" => "Hardware ID".to_owned(),
    "BusID" => "Bus ID".to_owned(),
    "Description" => "Description".to_owned(),
    "Connected" => "Connected".to_owned(),
    "ForceBind" => "Force Bind".to_owned(),
    "Bound" => "Bound".to_owned(),
    "Attached" => "Attached".to_owned(),
    "ClientIP" => "Client IP Address".to_owned(),
    "PersistedGUID" => "Persisted GUID".to_owned(),
    "StubInstanceID" => "Stub Instance ID".to_owned(),
    "WindowsUSBDevice" => "Windows USB Device".to_owned(),
    "Bind" => "Bind".to_owned(),
    "Unbind" => "Unbind".to_owned(),
    "Attach" => "Attach".to_owned(),
    "Detach" => "Detach".to_owned(),
    "Hide" => "Hide".to_owned(),
    "Show" => "Show".to_owned(),
    "ShowHide" => "Show Hidden".to_owned(),
    "AddToAuto" => "Add to Auto Attach".to_owned(),
    "RemoveFromAuto" => "Remove from Auto Attach".to_owned(),
    "DeleteSelected" => "Delete selected".to_owned(),
    "DeleteAll" => "Delete all".to_owned(),
    "PersistedDevices" => "Persisted Devices (Bound but not connected)".to_owned(),
    "AutoAttachHeaderTitle" => "Auto-attach devices".to_owned(),
    "Error" => "Error".to_owned(),
    "Note" => "Note".to_owned(),
    "NoDeviceSelected" => "No device is selected.".to_owned(),
    "NoConnectedDevice" => "No connected USB device is found.".to_owned(),
    "NoPersistedDevice" => "No persisted device is found.".to_owned(),
    "NoAutoDevice" => "The auto-attach list is empty.".to_owned(),
    "ShowingHiddenHint" => "Showing hidden devices now; use the context menu to restore them".to_owned(),
    "Loading" => "Loading...".to_owned(),
    "HistoryLogsCleared" => "History logs have been cleared.".to_owned(),
    "ConfigReset" => "Configuration has been restored to defaults.".to_owned(),
    "AnotherInstance" => "Another instance of the app is already running,\r\ncheck the system tray icon to restore the instance.".to_owned(),
    "UsbipdCheckFailed" => "usbipd-win check failed".to_owned(),
    "BindSuccess" => "Device bound".to_owned(),
    "UnbindSuccess" => "Device unbound".to_owned(),
    "AttachSuccess" => "Device attached to WSL".to_owned(),
    "DetachSuccess" => "Device detached from WSL".to_owned(),
    "AttachAllSuccess" => "All devices detached".to_owned(),
    "DeviceInAutoAttaching" => "The device is in auto-attaching.".to_owned(),
    "UsbipdNotInstalled" => "usbipd-win is not installed. Please visit https://github.com/dorssel/usbipd-win/releases to download and install usbipd-win V4.4.0 or higher, then restart this program.".to_owned(),
    "UsbipdLowVersion" => "The detected usbipd-win version is lower than V4.4.0. Please visit https://github.com/dorssel/usbipd-win/releases to download and install usbipd-win V4.4.0 or higher, then restart this program.".to_owned(),
    "UsbipdRemoteDisk" => "usbipd-win may be installed on a remote disk. Please install it on a local disk and restart this program.".to_owned(),
    "FirewallBlocked" => "A firewall appears to be blocking the connection from WSL.".to_owned(),
    "NoWslRunning" => "There is no WSL 2 distribution running; keep a WSL 2 distribution running.".to_owned(),
    "DeviceUsedByWindows" => "The device appears to be used by Windows; stop the service using it, or force bind the device before attaching.".to_owned(),
    "ErrMsgBindFail" => "Failed to bind device".to_owned(),
    "ErrMsgUnbindFail" => "Failed to unbind device".to_owned(),
    "ErrMsgAttachFail" => "Failed to attach device".to_owned(),
    "ErrMsgDetachFail" => "Failed to detach device".to_owned(),
    "ErrMsgDeviceNotConnected" => "not connected.".to_owned(),
    "ErrMsgDeviceNotBound" => "not bound.".to_owned(),
    "ErrNoNetCard" => "Network card is not available.".to_owned(),
    "ErrNetCardEmpty" => "Network card name is empty.".to_owned(),
    "ConnectedToWsl" => "connected to WSL".to_owned(),
    "ConnectedToWindows" => "connected to Windows".to_owned(),
    "Disconnected" => "disconnected".to_owned(),
    "AutoAttachDaemonExit" => "The automatic attachment program running in WSL has exited.".to_owned(),
    "CanceledByUser" => "The operation was canceled (the user declined the administrator prompt).".to_owned(),
        _ => key.to_owned(),
    }
}
